rvm:
  - 1.8.7 # (current default)
  - 1.9.2
  - 1.9.3
  - rbx
  - rbx-2.0
  - ree
  - jruby
  - rbx-18mode
before_script:
  - gem install isolate
  - gem install hoe
  - gem install rake-compiler
script: rake isolate test
