language: ruby

sudo: false

rvm:
- 2.0
- 2.1
- 2.2.5
- 2.3.1
- 2.4.0
- jruby-1.7
- jruby
- rbx

os:
- linux
- osx

matrix:
  allow_failures:
  # https://github.com/travis-ci/travis-ci/issues/5361
  - os: osx
    rvm: 2.2.5
  - os: osx
    rvm: 2.3.1
  - os: linux
    rvm: rbx
  exclude:
  - os: osx
    rvm: jruby-1.7
  - os: osx
    rvm: jruby
  - os: osx
    rvm: rbx

notifications:
  irc:
    channels:
      - "chat.freenode.net#nokogiri"
    on_success: always
    on_failure: always
    template:
      - "%{repository} (%{branch}:%{commit} by %{author}): %{message} (%{build_url})"
    skip_join: true
